version: '3'

services:
  redis:
    container_name: cache_roulette
    image: 'redis:alpine'    
    ports:
      - '6379:6379'
      - '6380:6380'
    networks:
      - sprint-network
  app:
    container_name: roulette_service    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"      
    env_file:
      - .env
    volumes:
      - .:/usr/src/app # Mount the current directory to the container
      - /usr/src/app/node_modules # Exclude node_modules from being overwritten
    command: npm run start:dev # Use NestJS watch mode
    networks:
      sprint-network:
        ipv4_address: 172.20.0.15