version: '3'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
      - '6380:6380'

  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: rouletteServiceDb
    volumes:
      - ./mongo:/data/dbs
  
